persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT (internal use or legacy)
listener 1883
allow_anonymous true

# Secure MQTT (External/TLS)
listener 8883
cafile /mosquitto/config/certs/rootCA.pem
certfile /mosquitto/config/certs/service.crt
keyfile /mosquitto/config/certs/service.key
require_certificate false
allow_anonymous true
